name: Clean Container Packager

on:
  workflow_call:
    inputs:
      repository_name:
        type: string
        required: true
      ref:
        type: string
        required: true
      actor:
        type: string
        required: true

jobs:
  delete-container-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      IMAGE_NAME: ${{ inputs.repository_name }}/${{ inputs.ref }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Container Package
        run: |
          curl -L \
            --fail-with-body \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/in-rich/packages/container/$(printf %s "${{ env.IMAGE_NAME }}"|jq -sRr @uri)
