name: Deploy Go

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      github_env:
        type: string
        required: true
      sha:
        type: string
        required: true
      job:
        type: string
        required: true
      project:
        type: string
        required: true
      main:
        type: string
        required: false
        default: ''
      timeout:
        type: string
        required: false
        default: '1om'
      retries:
        type: string
        required: false
        default: 3
    secrets:
      identity_provider:
        required: true
      service_account:
        required: true

jobs:
  deploy-go:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_env }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve Go packages
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: ./vendor/
      - name: Parse sources
        run: |
          if ${{ inputs.main != '' }}
          then
            mv ${{ inputs.main }} ./
          fi
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.identity_provider }}
          service_account: ${{ secrets.service_account }}
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          env_vars: |
            GOPRIVATE=github.com/in-rich/*
            ENV=${{ inputs.env }}
            RELEASE=${{ inputs.sha }}
          job: ${{ inputs.job }}
          region: europe-west9
          project_id: ${{ inputs.project }}
          source: ./
          flags: '--task-timeout ${{ inputs.timeout }} --max-retries ${{ inputs.retries }}'
